version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    container_name: go-client
    networks:
      - go-network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.server
    container_name: go-server
    networks:
      - go-network
    ports:
      - "8080:8080"

networks:
  go-network:
    driver: bridge
