
FROM golang:latest


# RUN mkdir server
# RUN mkdir grpc



# COPY ./server ./server
# COPY ./proto ./proto
# COPY go.mod .
# COPY go.sum .
# RUN go mod download




# EXPOSE 8080
# WORKDIR /dist

# CMD ["go", "run", "server/main.go"]

WORKDIR /dist
COPY go.mod .
COPY go.sum .
RUN go mod download


COPY ./server ./server
COPY ./proto ./proto

WORKDIR /dist/server

EXPOSE 8080
CMD ["go", "run", "."]
